// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEEEHmaUgLTbEHpF1sh6JWFw4ZETP_FNY',
    appId: '1:456847646187:web:664f7d0c6f530646620dae',
    messagingSenderId: '456847646187',
    projectId: 'eco-humboldt-go',
    authDomain: 'eco-humboldt-go.firebaseapp.com',
    storageBucket: 'eco-humboldt-go.firebasestorage.app',
    measurementId: 'G-F4S05JD7N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs64aw13bZbAiXwANJFDGSESfgIJUJYUc',
    appId: '1:456847646187:android:06885546f3d8c30b620dae',
    messagingSenderId: '456847646187',
    projectId: 'eco-humboldt-go',
    storageBucket: 'eco-humboldt-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3fAIcC-HrELcHTGnkYS3HDxI2QWtTdw',
    appId: '1:456847646187:ios:102f750f13ccd89a620dae',
    messagingSenderId: '456847646187',
    projectId: 'eco-humboldt-go',
    storageBucket: 'eco-humboldt-go.firebasestorage.app',
    iosBundleId: 'com.example.ecoHumboldtGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3fAIcC-HrELcHTGnkYS3HDxI2QWtTdw',
    appId: '1:456847646187:ios:102f750f13ccd89a620dae',
    messagingSenderId: '456847646187',
    projectId: 'eco-humboldt-go',
    storageBucket: 'eco-humboldt-go.firebasestorage.app',
    iosBundleId: 'com.example.ecoHumboldtGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEEEHmaUgLTbEHpF1sh6JWFw4ZETP_FNY',
    appId: '1:456847646187:web:a9afb8fbf8ae22ee620dae',
    messagingSenderId: '456847646187',
    projectId: 'eco-humboldt-go',
    authDomain: 'eco-humboldt-go.firebaseapp.com',
    storageBucket: 'eco-humboldt-go.firebasestorage.app',
    measurementId: 'G-WKW74F4ZQK',
  );

}